### PR TITLE
119 create basic threejs 3d component

### PR DESCRIPTION
**Pull request by lniehaus**
added a basic threejs component to the Crops3dView
There are probably some things, which are not correct in terms of ts or composition api (for example the excessive use of the any type)
would be cool if you could have a look on how to improve the code

### CODE REVIEW

**Comment by lniehaus** [comment]
somehow building the proto files fails

image

**Comment by lucaslootalot** [comment]
@lniehaus Who is responsible for this build?

**Comment by lniehaus** [comment]
> @lniehaus Who is responsible for this build?

I am not sure since i did not change any build related files. I created this branch out of dev with the Issue "new branch" function you showed me. 
For me it seems like the build in dev might not work as well but i am unsure on how to test the build Pipeline in dev. Maybe @Anafabula or @jarkenau can help.

**Comment by jarkenau** [comment]
The `grpcio-tools` package is missing, but I'm not sure why :thinking:

**Comment by Anafabula** [comment]
The pull request was pointed at the main branch, so it pulled the docker container from the main branch, which doesn't have `grpcio_tools`

**Comment by lniehaus** [comment]
> The pull request was pointed at the main branch, so it pulled the docker container from the main branch, which doesn't have `grpcio_tools`

Ah yeah, you are right. So it is not the branch which is broken but the "PR config" is? So restarting with the new "PR config" should do the trick.

**Comment by lniehaus** [comment]
> > > The pull request was pointed at the main branch, so it pulled the docker container from the main branch, which doesn't have `grpcio_tools`
> > 
> > 
> > Ah yeah, you are right. So it is not the branch which is broken but the "PR config" is? So restarting with the new "PR config" should do the trick.
> 
> I tried it but he does not seem to recognize to get the docker container from dev

hmm.. something strange happened. So I can validate your theory by creating a duplicated PR with the same code but a differently named branch. The PR was directly pointed to dev (instead of main, which then was changed to dev like I did in this PR). The build did complete successfully. But strangely now this PR builds successfully as well. It seems like github recognized to update the "PR config" and build this PR with the dev container.

**Review by lucaslootalot — APPROVED** [review]
lgtm 👍🏻

**Pull request merged**
