### PR TITLE
feat/sidebar

### PR DESCRIPTION
**Pull request by dobro929**

### CODE REVIEW

**Comment by dobro929** [comment]
Docker `ghcr.io/naturerobots/hsos-sep-plant-map-2022:35/merge` pull failed. @jarkenau can you take a look at this.

**Comment by jarkenau** [comment]
I think this line is causing the problem. https://github.com/naturerobots/HSOS-SEP-PlantMap-2022/blob/f202f041d073de4e6d383712985f3ad4ddf10ab4/.github/workflows/main.yml#L75 
It tries to get the image with the current branch name, but images are only built for the _dev_ and _main_  branch. @Anafabula can you take a look at this?

**Comment by Anafabula** [comment]
Looks like `github.ref_name` doesn't return anything helpful for pull requests. Looked at githubs docs and the best thing to do is probably replacing it with `${{ github.base_ref || github.ref_name }}`. That should work and grab the image for the target branch.

Problem is any changes to the docker configuration in the pr may be ignored. (Unless it overwrites the image if there are changes. I'm not sure what the build-docker job does in that case)

**Comment by lucaslootalot** [comment]
@Anafabula Could you make the changes and we'll just see what happens? The PR can then be taken back if it has no effect on this one.

**Comment by Anafabula** [comment]
I can once I'm at my PC in ~20 min

**Comment by Anafabula** [comment]
It worked (#37), but won't work for this branch unless you merge the changes from dev into it

**Pull request merged**
