### PR TITLE
ci: build docker images from PRs

### LINKED ISSUE #38: Potentially find a way to make CI build new docker images for PRs that change the config

### PR DESCRIPTION
**Pull request by Anafabula**
Build Docker images from pull requests only if the docker configuration was changed.
Otherwise use image from the target branch.

closes #38

### CODE REVIEW

**Comment by jarkenau** [comment]
Creating images for PRs is probably not the best idea because an image gets saved for every PR in the image registry.  https://github.com/naturerobots/HSOS-SEP-PlantMap-2022/pkgs/container/hsos-sep-plant-map-2022

**Comment by Anafabula** [comment]
It only makes a new one if the docker config changed, which shouldn't happen too often.

And idk how else to test changes to the docker config without breaking CI for other PRs/commits.

**Comment by jarkenau** [comment]
But all the images are still in the registry and won't be deleted. Why even create images from PRs? They will never be used by anyone. PRs should trigger the worklow for the `dev` or `main` branch.

**Comment by Anafabula** [comment]
> If the CI for the PR fails, you still got a working image. 

Not if the docker build succeeds and the main job doesn't. Before the fix, #48 would have broken CI for all the other PRs that were going on.

**Pull request merged**
