### PR TITLE
update docker setup and add demo data

### PR DESCRIPTION
**Pull request by jarkenau**

### CODE REVIEW

**Comment by lucaslootalot** [comment]
@jarkenau  What do I need to review here? 
@dobro929 The demo data you would have to take a look if you can work with it.

**Comment by jarkenau** [comment]
@lucaslootalot I just wanted to check, if your approval would be enough so that I could mege it.

**Review by lucaslootalot — APPROVED** [review]
lgtm ;)

**Comment by dobro929** [comment]
@lucaslootalot i have already checked those in #204.

**Pull request merged**
